version: '3.1'
services:
  authentication:
    build: MU-MNC002A-labs-auth/auth-app
    ports:
      - '13000:${UVICORN_PORT}'
    volumes:
      - './MU-MNC002A-labs-auth/auth-app/auth:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${AUTH_SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    networks:
      lb7_network:
        ipv4_address: '${USER_REPLICA1_IP}'
    restart: unless-stopped

  payment:
    build: MU-MNC002A-labs-payment/payment-app
    ports:
      - '11000:${UVICORN_PORT}'
    volumes:
      - './MU-MNC002A-labs-payment/payment-app/payment:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${PAYMENT_SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    depends_on:
      - "authentication"
    networks:
      lb7_network:
        ipv4_address: '${PAYMENT_REPLICA1_IP}'
    restart: unless-stopped

  log:
    build: MU-MNC002A-labs-logs/log-app
    ports:
      - '18000:${UVICORN_PORT}'
    volumes:
      - './MU-MNC002A-labs-logs/log-app/log:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${LOG_SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    networks:
      lb7_network:
        ipv4_address: '${LOG_REPLICA1_IP}'
    restart: on-failure

  machine:
    build: MU-MNC002A-labs-machine/machine-app
    ports:
      - '21000:${UVICORN_PORT}'
    volumes:
      - './MU-MNC002A-labs-machine/machine-app/machine:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${MACHINE_SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    networks:
      lb7_network:
        ipv4_address: '${MACHINE_REPLICA1_IP}'
    restart: on-failure

  delivery:
    build: MU-MNC002A-labs-delivery/delivery_app
    ports:
      - '20000:${UVICORN_PORT}'
    volumes:
      - './MU-MNC002A-labs-delivery/delivery_app/delivery:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${DELIVERY_SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    networks:
      lb7_network:
        ipv4_address: '${DELIVERY_REPLICA1_IP}'
    restart: on-failure

  order:
    build: MU-MNC002A-labs-order/order_app
    ports:
      - '19000:${UVICORN_PORT}'
    volumes:
      - './MU-MNC002A-labs-order/order_app/ms_order:/code'
      - './db_volume:/volume'
    environment:
      PYTHONUNBUFFERED: 1
      SQLALCHEMY_DATABASE_URL: ${ORDER_SQLALCHEMY_SQLITE_DATABASE_URI}
      LOG_CONFIG_FILENAME: ${LOG_CONFIG_FILENAME}
    networks:
      lb7_network:
        ipv4_address: '${ORDER_REPLICA1_IP}'
    restart: on-failure

  haproxy:
    image: haproxy:2.6-alpine
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
    expose:
      - '${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}'
    networks:
      lb7_network:
        ipv4_address: '${HAPROXY_IP}'
    environment:
      - 'USER_REPLICA1_IP=${USER_REPLICA1_IP}'
      - 'USER_REPLICA1_PORT=${UVICORN_PORT}'
      - 'PAYMENT_REPLICA1_IP=${PAYMENT_REPLICA1_IP}'
      - 'PAYMENT_REPLICA1_PORT=${UVICORN_PORT}'
      - 'LOG_REPLICA1_IP=${LOG_REPLICA1_IP}'
      - 'LOG_REPLICA1_PORT=${UVICORN_PORT}'
      - 'ORDER_REPLICA1_IP=${ORDER_REPLICA1_IP}'
      - 'ORDER_REPLICA1_PORT=${UVICORN_PORT}'
      - 'DELIVERY_REPLICA1_IP=${DELIVERY_REPLICA1_IP}'
      - 'DELIVERY_REPLICA1_PORT=${UVICORN_PORT}'
      - 'MACHINE_REPLICA1_IP=${MACHINE_REPLICA1_IP}'
      - 'MACHINE_REPLICA1_PORT=${UVICORN_PORT}'
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
    restart: unless-stopped
    volumes:
      - './haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg'
      - './certs/haproxy/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem'

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - "15671:15671"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SSL_VERIFY: verify_none
      RABBITMQ_SSL_CACERTFILE: /etc/ssl/certs/cert.pem
      RABBITMQ_SSL_CERTFILE: /etc/ssl/certs/rabbitmq_cert.pem
      RABBITMQ_SSL_KEYFILE: /etc/ssl/certs/rabbitmq_key.pem
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: false
    networks:
      lb7_network:
        ipv4_address: '${RABBITMQ_IP}'
    volumes:
      - './certs/rabbitmq/rabbitmq_cert.pem:/etc/ssl/certs/rabbitmq_cert.pem'
      - './certs/rabbitmq/rabbitmq_key.pem:/etc/ssl/certs/rabbitmq_key.pem'
      - './certs/rabbitmq/cert.pem:/etc/ssl/certs/cert.pem'

networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'